---
title: "R for Health Data Analysis(R4HDA)"
author: \textbf{Jubayer Hossain}
date: Sep 06, 2020
output:
  beamer_presentation: 
    fig_caption: yes
    fig_height: 6
    fig_width: 7
    fonttheme: structurebold
    theme: Madrid
classoption: "aspectratio=169"
---

## What is R?
- This is an easy question to answer. R is a dialect of S.
- R is a programming language and environment commonly used in **statistical computing**, **data analytics** and **scientific research**.
- It is one of the most popular languages used by **statisticians**, **data analysts**, **researchers** and **marketers to retrieve**, clean, analyze, **visualize** and present data.

## Why use R for statistical computing and graphics?
- R is open source and free!
- R is popular – and increasing in popularity
- R runs on all platforms
- R is being used by the biggest tech giants(google, facebook, microsoft, twitter)


## Applications of R Programming in Real World
- Data Science
- Data Analysis 
- Genomic Data Science 
- Biological Data Analysis 
- Mutational Signature Analysis 
- Genomic Analysis 
- Statistical Computing
- Machine Learning
